// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetConfig():Promise<main.AppConfig>;

export function SaveConfig(arg1:string,arg2:string):Promise<void>;

export function SelectDirectory():Promise<string>;
